version: "2"
services:
  eureka:
    image: eureka
    container_name: eureka
    build: ./eureka
    ports:
      - "8000:8000"
    network_mode: host

  gateway:
    image: gateway
    container_name: gateway
    build: ./gateway
    ports:
      - "8080:8080"
#    links:
#      - eureka
#      - authority
    depends_on:
      - eureka
    network_mode: host

  authority:
    image: authority
    container_name: authority
    build: ./authority
    ports:
        - "8081:8081"
#    links:
#      - eureka
    depends_on:
      - eureka
    network_mode: host