version: 2
services:
  eureka:
#    image: malefeng/eureka
    build: ./eureka
  authority:
    build: ./authority
    links:
      - eureka
    depends_on:
      - eureka
    ports:
      - "8081:8081"