version: "2"
services:
  eureka:
    image: eureka
    container_name: eureka
    build: ./eureka
#      context: ./eureka/
#      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  authority:
    image: authority
    container_name: authority
    build: ./authority
#      context: ./authority/
#      dockerfile: Dockerfile
    links:
      - eureka
    depends_on:
      - eureka
    ports:
      - "8081:8081"