version: "2"
services:
  eureka:
    container_name: eureka
    build:
      context: ./eureka/
      dockerfile: Dockerfile

  authority:
    container_name: authority
    build:
      context: ./authority/
      dockerfile: Dockerfile
    links:
      - eureka
    depends_on:
      - eureka
    ports:
      - "8081:8081"