version: "2"
services:
  eureka:
#    image: malefeng/eureka
    build: ./eureka/Dockerfile
  authority:
    build: ./authority/Dockerfile
    links:
      - eureka
    depends_on:
      - eureka
    ports:
      - "8081:8081"