version: "2"
services:
  eureka:
    image: eureka
    container_name: eureka
    build: ./eureka
    ports:
      - "8000:8000"

  gateway:
    image: gateway
    container_name: gateway
    build: ./gateway
    ports:
      - "8080:8080"
    depends_on:
      - eureka


  authority:
    image: authority
    container_name: authority
    build: ./authority
    ports:
        - "8081:8081"
    depends_on:
      - eureka