property:
  eureka_host: localhost



server:
  port: 8080

spring:
  cloud:
    inetutils:
      ignoredInterfaces:
        - docker0
        - veth.*

  application:
    name: gateway
#  zipkin:
#    base-url: http://localhost:9411
#  sleuth:
#    sampler:
#      probability: 1.0
#  cloud:
#    nacos:
#      discovery:
#        server-addr: http://localhost:8841
    gateway:
      routes:
        - id: authority
          uri: lb://authority
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1

        - id: test
          uri: lb://test
          predicates:
            - Path=/test/**
          filters:
            - StripPrefix=1
#    sentinel:
#      transport:
#        dashboard: localhost:8890
#        port: 8890
#      eager: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

eureka:
  client:
    service-url:
      defaultZone: http://${property.eureka_host}:8000/eureka