server:
  port: 8000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:${server.port}/eureka

spring:
  cloud:
    inetutils:
      ignoredInterfaces:
        - docker0
        - veth.*
  application:
    name: eureka
